services:
  awx-web:
    ports:
      - "0.0.0.0:${AWX_WEB_PORT:-18080}:8052"

  awx-receptor:
    ports:
      - "0.0.0.0:${AWX_RECEPTOR_PORT:-18888}:8888"

  gateway:
    ports:
      - "0.0.0.0:${GATEWAY_PORT:-18088}:8080"

  galaxy-ng:
    ports:
      - "0.0.0.0:${GALAXY_PORT:-15001}:8000"

  eda-controller:
    ports:
      - "0.0.0.0:${EDA_PORT:-15000}:5000"
