---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aax

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - awx-settings-configmap.yaml
  - awx-nginx-configmap.yaml
  - receptor-configs.yaml
  - persistent-volumes.yaml
  - ee-base-deployment.yaml
  - ee-builder-deployment.yaml
  - dev-tools-deployment.yaml
  - controller-stack.yaml
  - hub-stack.yaml
  - eda-stack.yaml
  - gateway-deployment.yaml

images:
  - name: aax/ee-base
    newTag: 1.0.0
  - name: aax/ee-builder
    newTag: 1.0.0
  - name: aax/dev-tools
    newTag: 1.0.0
  - name: aax/awx
    newTag: 1.0.0
  - name: aax/pulp
    newTag: 1.0.0
  - name: aax/galaxy-ng
    newTag: 1.0.0
  - name: aax/eda-controller
    newTag: 1.0.0
  - name: aax/gateway
    newTag: 1.0.0
