---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-receptor-config
  namespace: aax
  labels:
    app.kubernetes.io/name: awx-receptor-config
    app.kubernetes.io/part-of: aax
data:
  receptor.conf: |
    ---
    - node:
        id: receptor-controller
    - control-service:
        service: control
        filename: /var/lib/receptor/receptor.sock
        permissions: "0660"
    - tcp-listener:
        port: 8888
        bindaddr: 0.0.0.0
    - tcp-peer:
        address: receptor-hop:8888
    - log-level:
        level: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: receptor-hop-config
  namespace: aax
  labels:
    app.kubernetes.io/name: receptor-hop-config
    app.kubernetes.io/part-of: aax
data:
  receptor.conf: |
    ---
    - node:
        id: receptor-hop
    - control-service:
        service: control
        filename: /var/lib/receptor/receptor.sock
        permissions: "0660"
    - tcp-listener:
        port: 8888
        bindaddr: 0.0.0.0
    - tcp-peer:
        address: awx-receptor:8888
    - tcp-peer:
        address: receptor-execution:8888
    - log-level:
        level: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: receptor-execution-config
  namespace: aax
  labels:
    app.kubernetes.io/name: receptor-execution-config
    app.kubernetes.io/part-of: aax
data:
  receptor.conf: |
    ---
    - node:
        id: receptor-execution
    - control-service:
        service: control
        filename: /var/lib/receptor/receptor.sock
        permissions: "0660"
    - tcp-listener:
        port: 8888
        bindaddr: 0.0.0.0
    - tcp-peer:
        address: receptor-hop:8888
    - work-command:
        worktype: ansible-runner
        command: ansible-runner
        params: worker
        allowruntimeparams: true
    - log-level:
        level: info
