---
all:
  children:
    raspberry_pi:
      vars:
        ansible_user: "{{ lookup('env', 'PI_SSH_USER') | default('ansible', true) }}"
        ansible_python_interpreter: /usr/bin/python3
      children:
        dns_pair:
          children:
            dns_replica:
              hosts:
                pi-harmony:
                  ansible_host: 192.168.5.54
            dns_primary:
              hosts:
                pi-terror:
                  ansible_host: 192.168.5.52
        mdns:
          hosts:
            pi-mdns:
              ansible_host: 192.168.5.101

    draytek:
      children:
        draytek_router:
          hosts:
            HomeOne:
              ansible_host: 192.168.5.1
              device_model: Vigor2927Lac
              expected_firmware: 4.5.2.2
        draytek_managed_switches:
          hosts:
            MilSwitch:
              ansible_host: 192.168.5.2
              device_model: G2100
              expected_firmware: 2.9.11
            KPOffice:
              ansible_host: 192.168.5.3
              device_model: G2100
              expected_firmware: 2.9.11
        draytek_light_switches:
          hosts:
            KPShelf:
              ansible_host: 192.168.5.5
              device_model: G1080
              expected_firmware: 1.05.00
            TVRoom:
              ansible_host: 192.168.5.6
              device_model: G1080
              expected_firmware: 1.05.00
            KidsRoom:
              ansible_host: 192.168.5.7
              device_model: G1080
              expected_firmware: 1.05.00
        draytek_mesh:
          hosts:
            KidsMesh:
              ansible_host: 192.168.5.10
              device_model: VigorAP1060C
              expected_firmware: 1.4.12
            OfficeMesh:
              ansible_host: 192.168.5.11
              device_model: VigorAP918R
              expected_firmware: 1.4.11

    synology:
      hosts:
        alexandria:
          ansible_host: 192.168.5.100
          device_model: DS920+
          expected_dsm_version: 7.4.1-90080
