---
all:
  children:
    raspberry_pi:
      vars:
        ansible_user: "{{ lookup('env', 'PI_SSH_USER') | default('ansible', true) }}"
        ansible_python_interpreter: /usr/bin/python3
      children:
        dns_pair:
          children:
            dns_replica:
              hosts:
                pi-harmony:
                  ansible_host: 192.168.5.54
            dns_primary:
              hosts:
                pi-terror:
                  ansible_host: 192.168.5.52
        mdns:
          hosts:
            pi-mdns:
              ansible_host: 192.168.5.101

    draytek:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: ansible.netcommon.default
        ansible_command_timeout: 60
      hosts: {}
